modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="mmp"
version="1.7.1"
displayName="Mekanism: More Prefix"
authors="Tau34"

description='''${mod_description}'''
[[dependencies.mmp]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mmp]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mmp]]
modId="mekanismgenerators"
mandatory=true
versionRange="[10.4.0.14,)"
ordering="NONE"
side="BOTH"